import Foundation

/// Plain-English titles for common SAE-generic DTCs (Mode $03).
enum DTCDatabase {

    static let titles: [String: String] = [
        // Fuel & air metering
        "P0001": "Fuel volume regulator control circuit open",
        "P0002": "Fuel volume regulator control circuit range/performance",
        "P0003": "Fuel volume regulator control circuit low",
        "P0010": "Camshaft position actuator circuit open (bank 1)",
        "P0011": "Camshaft position — timing over-advanced (bank 1)",
        "P0012": "Camshaft position — timing over-retarded (bank 1)",
        "P0013": "Camshaft position actuator circuit open (bank 2)",
        "P0016": "Crankshaft/camshaft position correlation (bank 1)",
        "P0030": "HO2S heater control circuit (bank 1 sensor 1)",
        "P0031": "HO2S heater control circuit low (bank 1 sensor 1)",
        "P0036": "HO2S heater control circuit (bank 1 sensor 2)",
        "P0087": "Fuel rail pressure too low",
        "P0088": "Fuel rail pressure too high",
        "P0090": "Fuel pressure regulator control circuit",
        "P0100": "Mass air flow (MAF) sensor circuit",
        "P0101": "MAF sensor circuit range/performance",
        "P0102": "MAF sensor circuit low input",
        "P0103": "MAF sensor circuit high input",
        "P0105": "Manifold absolute pressure (MAP) sensor circuit",
        "P0106": "MAP sensor range/performance",
        "P0107": "MAP sensor input low",
        "P0108": "MAP sensor input high",
        "P0110": "Intake air temperature sensor circuit",
        "P0111": "Intake air temperature sensor range/performance",
        "P0112": "Intake air temperature sensor low input",
        "P0113": "Intake air temperature sensor high input",
        "P0115": "Engine coolant temperature sensor circuit",
        "P0116": "Coolant temperature sensor range/performance",
        "P0117": "Coolant temperature sensor low input",
        "P0118": "Coolant temperature sensor high input",
        "P0120": "Throttle position sensor A circuit",
        "P0121": "Throttle position sensor A range/performance",
        "P0122": "Throttle position sensor A low input",
        "P0123": "Throttle position sensor A high input",
        "P0125": "Insufficient coolant temperature for closed-loop fuel control",
        "P0128": "Coolant thermostat below regulating temperature",
        "P0130": "O2 sensor circuit (bank 1 sensor 1)",
        "P0131": "O2 sensor circuit low voltage (bank 1 sensor 1)",
        "P0132": "O2 sensor circuit high voltage (bank 1 sensor 1)",
        "P0133": "O2 sensor circuit slow response (bank 1 sensor 1)",
        "P0134": "O2 sensor no activity detected (bank 1 sensor 1)",
        "P0135": "O2 sensor heater circuit (bank 1 sensor 1)",
        "P0136": "O2 sensor circuit (bank 1 sensor 2)",
        "P0137": "O2 sensor circuit low voltage (bank 1 sensor 2)",
        "P0138": "O2 sensor circuit high voltage (bank 1 sensor 2)",
        "P0140": "O2 sensor no activity detected (bank 1 sensor 2)",
        "P0141": "O2 sensor heater circuit (bank 1 sensor 2)",
        "P0170": "Fuel trim malfunction (bank 1)",
        "P0171": "System too lean (bank 1)",
        "P0172": "System too rich (bank 1)",
        "P0174": "System too lean (bank 2)",
        "P0175": "System too rich (bank 2)",
        "P0183": "Fuel temperature sensor high input",
        "P0190": "Fuel rail pressure sensor circuit",
        "P0191": "Fuel rail pressure sensor range/performance",
        "P0193": "Fuel rail pressure sensor high input",
        // Injectors & ignition
        "P0201": "Injector circuit open — cylinder 1",
        "P0202": "Injector circuit open — cylinder 2",
        "P0203": "Injector circuit open — cylinder 3",
        "P0204": "Injector circuit open — cylinder 4",
        "P0205": "Injector circuit open — cylinder 5",
        "P0206": "Injector circuit open — cylinder 6",
        "P0207": "Injector circuit open — cylinder 7",
        "P0208": "Injector circuit open — cylinder 8",
        "P0217": "Engine over-temperature condition",
        "P0218": "Transmission over-temperature condition",
        "P0230": "Fuel pump primary circuit malfunction",
        "P0231": "Fuel pump secondary circuit low",
        "P0232": "Fuel pump secondary circuit high",
        "P0234": "Turbocharger/supercharger overboost condition",
        "P0235": "Turbo boost sensor circuit malfunction",
        // Misfires
        "P0299": "Turbocharger/supercharger underboost",
        "P0300": "Random/multiple cylinder misfire detected",
        "P0301": "Cylinder 1 misfire detected",
        "P0302": "Cylinder 2 misfire detected",
        "P0303": "Cylinder 3 misfire detected",
        "P0304": "Cylinder 4 misfire detected",
        "P0305": "Cylinder 5 misfire detected",
        "P0306": "Cylinder 6 misfire detected",
        "P0307": "Cylinder 7 misfire detected",
        "P0308": "Cylinder 8 misfire detected",
        "P0327": "Knock sensor circuit low (bank 1)",
        "P0335": "Crankshaft position sensor A circuit",
        "P0336": "Crankshaft position sensor A range/performance",
        "P0340": "Camshaft position sensor A circuit (bank 1)",
        "P0341": "Camshaft position sensor A range/performance (bank 1)",
        // Aux emissions
        "P0400": "Exhaust gas recirculation (EGR) flow malfunction",
        "P0401": "EGR flow insufficient detected",
        "P0402": "EGR flow excessive detected",
        "P0403": "EGR control circuit malfunction",
        "P0404": "EGR control circuit range/performance",
        "P0420": "Catalyst system efficiency below threshold (bank 1)",
        "P0430": "Catalyst system efficiency below threshold (bank 2)",
        "P0440": "Evaporative emission (EVAP) control system malfunction",
        "P0441": "EVAP system incorrect purge flow",
        "P0442": "EVAP system small leak detected",
        "P0443": "EVAP purge control valve circuit malfunction",
        "P0446": "EVAP vent control circuit malfunction",
        "P0455": "EVAP system gross leak detected",
        "P0456": "EVAP system very small leak detected",
        // Speed / idle / output
        "P0500": "Vehicle speed sensor malfunction",
        "P0501": "Vehicle speed sensor range/performance",
        "P0505": "Idle air control system malfunction",
        "P0506": "Idle air control system RPM lower than expected",
        "P0507": "Idle air control system RPM higher than expected",
        "P0562": "System voltage low",
        "P0563": "System voltage high",
        "P0601": "Internal control module memory checksum error",
        "P0603": "Internal control module keep-alive memory error",
        "P0606": "ECU processor malfunction",
        "P0615": "Starter relay circuit malfunction",
        "P0700": "Transmission control system malfunction",
        "P0715": "Input/turbine speed sensor circuit malfunction",
        "P0720": "Output speed sensor circuit malfunction",
        "P0730": "Incorrect gear ratio",
        "P0740": "Torque converter clutch circuit malfunction",
        "P0741": "Torque converter clutch stuck off",
        // Chassis / body / network (common ones)
        "C0035": "Left front wheel speed sensor circuit",
        "C0040": "Right front wheel speed sensor circuit",
        "C0265": "EBTCM relay contact circuit",
        "B1342": "ECU internal malfunction",
        "U0100": "Lost communication with ECM/PCM",
        "U0101": "Lost communication with TCM",
        "U0121": "Lost communication with ABS control module",
        "U0140": "Lost communication with body control module",
        "U0155": "Lost communication with instrument panel cluster"
    ]

    static func title(for code: String) -> (title: String, known: Bool) {
        if let t = titles[code.uppercased()] {
            return (t, true)
        }
        let prefix = String(code.prefix(1)).uppercased()
        switch prefix {
        case "P": return ("Powertrain code — see service manual for details", false)
        case "C": return ("Chassis code (ABS/suspension) — see service manual", false)
        case "B": return ("Body code (comfort/interior) — see service manual", false)
        case "U": return ("Network communication code — see service manual", false)
        default: return ("Unknown code", false)
        }
    }
}
